
import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr' | 'de' | 'it' | 'zh' | 'jp';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcomeMessage: 'Welcome to DUMONT Professional Tools',
    heroTitle: 'Precision Tools for Professional Excellence',
    heroSubtitle: 'Discover our comprehensive range of professional-grade tools and equipment, trusted by industries worldwide for over 75 years.',
    getStarted: 'Get Started',
    browseProducts: 'Browse Products',
    totalProducts: 'Total Products',
    countries: 'Countries Served',
    languages: 'Languages',
    currencies: 'Currencies',
    featuresTitle: 'Why Choose DUMONT?',
    featuresSubtitle: 'Built for professionals who demand the highest quality and reliability.',
    securityTitle: 'Enterprise Security',
    securityDescription: 'PCI compliant with enterprise-grade security features',
    speedTitle: 'Lightning Fast',
    speedDescription: 'Optimized for speed with modern technology stack',
    globalTitle: 'Global Reach',
    globalDescription: 'Multi-currency, multi-language, multi-country support',
    b2bTitle: 'B2B & B2C',
    b2bDescription: 'Hybrid platform serving both business and consumer needs',
    featuredProducts: 'Featured Products',
    featuredProductsSubtitle: 'Discover our most popular professional tools',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    addToCart: 'Add to Cart',
    viewAllProducts: 'View All Products',
    searchPlaceholder: 'Search products, codes, serial numbers...',
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    products: 'Products',
    configurator: 'Configurator',
    industries: 'Industries',
    support: 'Support',
    about: 'About',
    // Auth
    authentication: 'Authentication',
    email: 'Email',
    password: 'Password',
    loggingIn: 'Logging in...',
    loginSuccess: 'Login Successful',
    welcomeBack: 'Welcome back!',
    loginError: 'Login Error',
    invalidCredentials: 'Invalid email or password',
    forgotPassword: 'Forgot Password?',
    // Registration
    fullName: 'Full Name',
    company: 'Company',
    legalStatus: 'Legal Status',
    selectLegalStatus: 'Select legal status',
    fieldOfActivity: 'Field of Activity',
    roleInCompany: 'Role in Company',
    phone: 'Phone',
    companyWebsite: 'Company Website',
    taxId: 'Tax ID',
    eori: 'EORI Number',
    preferredPaymentMethod: 'Preferred Payment Method',
    selectPaymentMethod: 'Select payment method',
    creditCard: 'Credit Card',
    bankTransfer: 'Bank Transfer',
    paymentTerms: 'Payment Terms',
    specialInstructions: 'Special Instructions',
    submitRegistration: 'Submit Registration',
    submitting: 'Submitting...',
    registrationSubmitted: 'Registration Submitted',
    registrationPendingReview: 'Your registration is pending review. We will contact you shortly.',
    registrationError: 'Registration Error',
    registrationErrorMessage: 'There was an error submitting your registration. Please try again.',
    // Footer
    footerDescription: 'Leading manufacturer of precision tools and equipment for professional industries worldwide.',
    tweezers: 'Tweezers',
    pliers: 'Pliers',
    cuttingTools: 'Cutting Tools',
    documentation: 'Documentation',
    technicalSupport: 'Technical Support',
    warranty: 'Warranty',
    returns: 'Returns',
    legal: 'Legal',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    gdprCompliance: 'GDPR Compliance',
    cookiePolicy: 'Cookie Policy',
    allRightsReserved: 'All rights reserved.'
  },
  fr: {
    welcomeMessage: 'Bienvenue chez DUMONT Outils Professionnels',
    heroTitle: 'Outils de Précision pour l\'Excellence Professionnelle',
    heroSubtitle: 'Découvrez notre gamme complète d\'outils et équipements de qualité professionnelle, utilisés par les industries du monde entier depuis plus de 75 ans.',
    getStarted: 'Commencer',
    browseProducts: 'Parcourir les Produits',
    totalProducts: 'Produits Totaux',
    countries: 'Pays Desservis',
    languages: 'Langues',
    currencies: 'Devises',
    featuresTitle: 'Pourquoi Choisir DUMONT?',
    featuresSubtitle: 'Conçu pour les professionnels qui exigent la plus haute qualité et fiabilité.',
    securityTitle: 'Sécurité Entreprise',
    securityDescription: 'Conforme PCI avec des fonctionnalités de sécurité de niveau entreprise',
    speedTitle: 'Ultra Rapide',
    speedDescription: 'Optimisé pour la vitesse avec une pile technologique moderne',
    globalTitle: 'Portée Mondiale',
    globalDescription: 'Support multi-devises, multi-langues, multi-pays',
    b2bTitle: 'B2B & B2C',
    b2bDescription: 'Plateforme hybride servant les besoins professionnels et grand public',
    featuredProducts: 'Produits Vedettes',
    featuredProductsSubtitle: 'Découvrez nos outils professionnels les plus populaires',
    inStock: 'En Stock',
    outOfStock: 'Rupture de Stock',
    addToCart: 'Ajouter au Panier',
    viewAllProducts: 'Voir Tous les Produits',
    searchPlaceholder: 'Rechercher produits, codes, numéros de série...',
    login: 'Connexion',
    logout: 'Déconnexion',
    register: 'S\'inscrire',
    products: 'Produits',
    configurator: 'Configurateur',
    industries: 'Industries',
    support: 'Support',
    about: 'À propos'
    // Add more French translations as needed
  },
  de: {
    welcomeMessage: 'Willkommen bei DUMONT Professionelle Werkzeuge',
    heroTitle: 'Präzisionswerkzeuge für Professionelle Exzellenz',
    heroSubtitle: 'Entdecken Sie unser umfassendes Sortiment an professionellen Werkzeugen und Geräten, das seit über 75 Jahren von Industrien weltweit vertraut wird.',
    getStarted: 'Loslegen',
    browseProducts: 'Produkte Durchsuchen',
    totalProducts: 'Gesamtprodukte',
    countries: 'Bediente Länder',
    languages: 'Sprachen',
    currencies: 'Währungen',
    featuresTitle: 'Warum DUMONT Wählen?',
    featuresSubtitle: 'Entwickelt für Profis, die höchste Qualität und Zuverlässigkeit fordern.',
    securityTitle: 'Unternehmenssicherheit',
    securityDescription: 'PCI-konform mit unternehmenstauglichen Sicherheitsfeatures',
    speedTitle: 'Blitzschnell',
    speedDescription: 'Für Geschwindigkeit mit modernem Technologie-Stack optimiert',
    globalTitle: 'Globale Reichweite',
    globalDescription: 'Multi-Währungs-, Multi-Sprach-, Multi-Land-Support',
    b2bTitle: 'B2B & B2C',
    b2bDescription: 'Hybrid-Plattform für Geschäfts- und Verbraucherbedürfnisse',
    featuredProducts: 'Empfohlene Produkte',
    featuredProductsSubtitle: 'Entdecken Sie unsere beliebtesten professionellen Werkzeuge',
    inStock: 'Auf Lager',
    outOfStock: 'Nicht Vorrätig',
    addToCart: 'In den Warenkorb',
    viewAllProducts: 'Alle Produkte Anzeigen',
    searchPlaceholder: 'Produkte, Codes, Seriennummern suchen...',
    login: 'Anmelden',
    logout: 'Abmelden',
    register: 'Registrieren',
    products: 'Produkte',
    configurator: 'Konfigurator',
    industries: 'Industrien',
    support: 'Support',
    about: 'Über uns'
    // Add more German translations as needed
  },
  it: {
    welcomeMessage: 'Benvenuti in DUMONT Strumenti Professionali',
    heroTitle: 'Strumenti di Precisione per l\'Eccellenza Professionale',
    heroSubtitle: 'Scopri la nostra gamma completa di strumenti e attrezzature di livello professionale, di cui si fidano le industrie di tutto il mondo da oltre 75 anni.',
    getStarted: 'Inizia',
    browseProducts: 'Sfoglia Prodotti',
    totalProducts: 'Prodotti Totali',
    countries: 'Paesi Serviti',
    languages: 'Lingue',
    currencies: 'Valute',
    featuresTitle: 'Perché Scegliere DUMONT?',
    featuresSubtitle: 'Costruito per professionisti che richiedono la massima qualità e affidabilità.',
    securityTitle: 'Sicurezza Aziendale',
    securityDescription: 'Conforme PCI con funzionalità di sicurezza di livello aziendale',
    speedTitle: 'Velocità Fulminea',
    speedDescription: 'Ottimizzato per la velocità con stack tecnologico moderno',
    globalTitle: 'Portata Globale',
    globalDescription: 'Supporto multi-valuta, multi-lingua, multi-paese',
    b2bTitle: 'B2B & B2C',
    b2bDescription: 'Piattaforma ibrida che serve esigenze business e consumer',
    featuredProducts: 'Prodotti in Evidenza',
    featuredProductsSubtitle: 'Scopri i nostri strumenti professionali più popolari',
    inStock: 'Disponibile',
    outOfStock: 'Esaurito',
    addToCart: 'Aggiungi al Carrello',
    viewAllProducts: 'Visualizza Tutti i Prodotti',
    searchPlaceholder: 'Cerca prodotti, codici, numeri di serie...',
    login: 'Accedi',
    logout: 'Esci',
    register: 'Registrati',
    products: 'Prodotti',
    configurator: 'Configuratore',
    industries: 'Industrie',
    support: 'Supporto',
    about: 'Chi Siamo'
    // Add more Italian translations as needed
  },
  zh: {
    welcomeMessage: '欢迎来到DUMONT专业工具',
    heroTitle: '专业卓越的精密工具',
    heroSubtitle: '发现我们全面的专业级工具和设备系列，75年来受到全球行业的信赖。',
    getStarted: '开始使用',
    browseProducts: '浏览产品',
    totalProducts: '产品总数',
    countries: '服务国家',
    languages: '语言',
    currencies: '货币',
    featuresTitle: '为什么选择DUMONT？',
    featuresSubtitle: '为要求最高质量和可靠性的专业人士而构建。',
    securityTitle: '企业安全',
    securityDescription: 'PCI合规，具有企业级安全功能',
    speedTitle: '闪电般快速',
    speedDescription: '采用现代技术栈优化速度',
    globalTitle: '全球覆盖',
    globalDescription: '多货币、多语言、多国家支持',
    b2bTitle: 'B2B和B2C',
    b2bDescription: '服务企业和消费者需求的混合平台',
    featuredProducts: '精选产品',
    featuredProductsSubtitle: '发现我们最受欢迎的专业工具',
    inStock: '有库存',
    outOfStock: '缺货',
    addToCart: '添加到购物车',
    viewAllProducts: '查看所有产品',
    searchPlaceholder: '搜索产品、代码、序列号...',
    login: '登录',
    logout: '登出',
    register: '注册',
    products: '产品',
    configurator: '配置器',
    industries: '行业',
    support: '支持',
    about: '关于我们'
    // Add more Chinese translations as needed
  },
  jp: {
    welcomeMessage: 'DUMONTプロフェッショナルツールへようこそ',
    heroTitle: 'プロフェッショナルエクセレンスのための精密ツール',
    heroSubtitle: '75年以上にわたって世界の産業界から信頼されている、当社の包括的なプロフェッショナルグレードのツールと装置をご覧ください。',
    getStarted: '始める',
    browseProducts: '製品を閲覧',
    totalProducts: '総製品数',
    countries: 'サービス提供国',
    languages: '言語',
    currencies: '通貨',
    featuresTitle: 'なぜDUMONTを選ぶのか？',
    featuresSubtitle: '最高の品質と信頼性を求めるプロフェッショナルのために構築されています。',
    securityTitle: 'エンタープライズセキュリティ',
    securityDescription: 'エンタープライズグレードのセキュリティ機能を備えたPCI準拠',
    speedTitle: '超高速',
    speedDescription: 'モダンテクノロジースタックで速度を最適化',
    globalTitle: 'グローバルリーチ',
    globalDescription: 'マルチ通貨、マルチ言語、マルチ国サポート',
    b2bTitle: 'B2BとB2C',
    b2bDescription: 'ビジネスと消費者のニーズに対応するハイブリッドプラットフォーム',
    featuredProducts: '注目製品',
    featuredProductsSubtitle: '最も人気のあるプロフェッショナルツールをご覧ください',
    inStock: '在庫あり',
    outOfStock: '在庫切れ',
    addToCart: 'カートに追加',
    viewAllProducts: 'すべての製品を見る',
    searchPlaceholder: '製品、コード、シリアル番号を検索...',
    login: 'ログイン',
    logout: 'ログアウト',
    register: '登録',
    products: '製品',
    configurator: 'コンフィギュレーター',
    industries: '産業',
    support: 'サポート',
    about: '会社について'
    // Add more Japanese translations as needed
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
